"""
skill_effects_generated.py - 自动生成，请勿手动编辑。

由 scripts/generate_skill_effects.py 从数据库 description 批量生成。
"""

from src.effect_models import E, EffectTag, SkillTiming
from src.effect_data import T, SE

SKILL_EFFECTS_GENERATED = {
    "一拳": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "三连破": [
        SE(SkillTiming.PRE_USE, [T(E.SELF_BUFF, atk=0.3)]),
        SE(SkillTiming.ON_USE, [T(E.SKILL_MOD, target='self', stat='hit_count', value=3)]),
    ],
    "三鼓作气": [
        SE(SkillTiming.PRE_USE, [T(E.SELF_BUFF, atk=0.3)]),
        SE(SkillTiming.ON_USE, [T(E.SKILL_MOD, target='self', stat='hit_count', value=3)]),
    ],
    "不动如山": [SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.9)])],
    "不可接触": [SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.5), T(E.POISON, stacks=1)])],
    "丢冰块": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "主场优势": [],
    "主轴": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "乘胜追击": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.POST_USE, [T(E.PERMANENT_MOD, target='hit_count', delta=1, trigger='per_use')]),
    ],
    "乘风": [SE(SkillTiming.PRE_USE, [T(E.SELF_BUFF, speed=1.2)])],
    "乱打": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "二律背反": [
        SE(SkillTiming.ON_USE, [T(E.METEOR, stacks=3)]),
        SE(SkillTiming.ON_COUNTER, [], category='defense'),
    ],
    "交叉闪电": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "仙人掌刺击": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "以重制重": [],
    "休息回复": [SE(SkillTiming.ON_USE, [T(E.HEAL_HP, pct=0.3)])],
    "传感器": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "伪造账单": [],
    "伺机而动": [SE(SkillTiming.ON_USE, [T(E.NEXT_ATTACK_MOD, power_bonus=70)])],
    "俯冲猛击": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "借用": [],
    "假寐": [SE(SkillTiming.ON_USE, [T(E.HEAL_ENERGY, amount=2)])],
    "偷师": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "充分燃烧": [],
    "先发制人": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "光之矛": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "光刃": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "光合作用": [],
    "光球": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "光能聚集": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "冥想": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.7)]),
        SE(SkillTiming.ON_COUNTER, [], category='attack'),
    ],
    "冬至": [SE(SkillTiming.ON_USE, [T(E.WEATHER, {"type": 'snow'}, turns=8)])],
    "冰冻光线": [SE(SkillTiming.ON_USE, [T(E.DAMAGE), T(E.SKILL_MOD, target='enemy', stat='cost', value=2)])],
    "冰刺": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.ON_COUNTER, [], category='status'),
    ],
    "冰墙": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.7)]),
        SE(SkillTiming.ON_COUNTER, [], category='attack'),
    ],
    "冰天雪地": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.7)]),
        SE(SkillTiming.ON_COUNTER, [], category='attack'),
    ],
    "冰捆缚": [SE(SkillTiming.ON_USE, [T(E.SKILL_MOD, target='enemy', stat='cost', value=1), T(E.SKILL_MOD, target='self', stat='hit_count', value=2)])],
    "冰晶坠": [SE(SkillTiming.ON_USE, [T(E.DAMAGE), T(E.SKILL_MOD, target='enemy', stat='cost', value=1)])],
    "冰点": [
        SE(SkillTiming.ON_USE, [T(E.FREEZE, stacks=5)]),
        SE(SkillTiming.ON_COUNTER, [], category='defense'),
    ],
    "冰爪": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "冰荆棘": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.7)]),
        SE(SkillTiming.ON_COUNTER, [], category='attack'),
    ],
    "冰蛋壳": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.6)]),
        SE(SkillTiming.ON_COUNTER, [], category='attack'),
    ],
    "冰锋横扫": [],
    "冰锥": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "冰雹": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.ON_COUNTER, [T(E.SKILL_MOD, target='enemy', stat='cost', value=3), T(E.ENEMY_ENERGY_COST_UP, amount=3, filter='all')], category='status'),
    ],
    "冲击": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "冲撞": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.POST_USE, [T(E.PERMANENT_MOD, target='cost', delta=-1, trigger='per_use')]),
    ],
    "冷风": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "击鼓传花": [SE(SkillTiming.ON_USE, [T(E.FORCE_SWITCH)])],
    "刺盾": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.7)]),
        SE(SkillTiming.ON_COUNTER, [T(E.ENEMY_DEBUFF, atk=0.5)], category='attack'),
    ],
    "刺藤": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "剧毒": [
        SE(SkillTiming.ON_USE, [T(E.POISON, stacks=3)]),
        SE(SkillTiming.ON_COUNTER, [], category='defense'),
    ],
    "力量吞噬": [SE(SkillTiming.ON_USE, [T(E.SKILL_MOD, target='self', stat='power', value=20), T(E.SKILL_MOD, target='enemy', stat='power', value=-20)])],
    "加固": [SE(SkillTiming.PRE_USE, [T(E.SELF_BUFF, {"def": 1.4})])],
    "加大功率": [SE(SkillTiming.ON_USE, [T(E.FORCE_SWITCH)])],
    "勾魂": [SE(SkillTiming.ON_USE, [T(E.STEAL_ENERGY, amount=3)])],
    "化劲": [SE(SkillTiming.ON_USE, [T(E.SKILL_MOD, target='self', stat='power_pct', value=0.4)])],
    "升龙咆哮": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "午夜噪音": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "压扁": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "双响炮": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "双联脉冲": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "反击拳": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "反弹": [],
    "取念": [],
    "叠势": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "叶绿光束": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "后发制人": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "吞噬": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "吨位压制": [],
    "吹火": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.POST_USE, [T(E.PERMANENT_MOD, target='power', delta=20, trigger='per_use')]),
    ],
    "吹炎": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.ON_COUNTER, [T(E.POWER_DYNAMIC, condition='counter', multiplier=2.0)], category='status'),
    ],
    "咆哮": [SE(SkillTiming.PRE_USE, [T(E.ENEMY_DEBUFF, atk=1.3)])],
    "啃咬": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "啄击": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "嗜痛": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.7)]),
        SE(SkillTiming.ON_COUNTER, [T(E.SELF_BUFF, atk=0.2, spatk=0.2)], category='attack'),
    ],
    "噬心": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "四维降解": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "回旋风暴": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "地陷": [
        SE(SkillTiming.PRE_USE, [T(E.SELF_BUFF, {"def": 0.6})]),
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.ON_COUNTER, [T(E.POWER_DYNAMIC, condition='counter', multiplier=2.0)], category='status'),
    ],
    "地震": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "坍缩": [
        SE(SkillTiming.PRE_USE, [T(E.SELF_BUFF, spatk=0.5)]),
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
    ],
    "坟场搏击": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "垂死反击": [SE(SkillTiming.ON_USE, [T(E.DAMAGE), T(E.POWER_DYNAMIC, condition='self_missing_hp_step', step_pct=0.05, bonus_per_step=5)])],
    "埋伏": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.IF, [T(E.SKILL_MOD, target='self', stat='current_hit_count', value=4, condition='enemy_switch')], enemy_switch=True),
    ],
    "堆雪人": [
        SE(SkillTiming.PRE_USE, [T(E.ENEMY_DEBUFF, spdef=0.2)]),
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
    ],
    "增程电池": [],
    "壁垒": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.9)]),
        SE(SkillTiming.ON_COUNTER, [], category='attack'),
    ],
    "复写": [],
    "多维击打": [SE(SkillTiming.ON_USE, [T(E.DAMAGE), T(E.METEOR, stacks=1)])],
    "大爆炸": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "天光": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "天旋地转": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "天火": [
        SE(SkillTiming.ON_USE, [T(E.BURN, stacks=10)]),
        SE(SkillTiming.ON_COUNTER, [], category='defense'),
    ],
    "孢子": [SE(SkillTiming.ON_USE, [T(E.LEECH, stacks=1)])],
    "孢子爆散": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.POST_USE, [T(E.PERMANENT_MOD, target='hit_count', delta=2, trigger='per_use')]),
    ],
    "寄生种子": [],
    "富养化": [SE(SkillTiming.ON_USE, [T(E.HEAL_ENERGY, amount=3)])],
    "寒风吹": [
        SE(SkillTiming.PRE_USE, [T(E.ENEMY_DEBUFF, spdef=0.4)]),
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
    ],
    "寸拳": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "导电撞击": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "小偷小摸": [SE(SkillTiming.ON_USE, [T(E.STEAL_ENERGY, amount=3)])],
    "尾后针": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "山火": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "岩土暴击": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "岩脉崩毁": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "幻象": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "幼态延续": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "幽灵爆发": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "应激反应": [SE(SkillTiming.ON_COUNTER, [], category='defense')],
    "引雷": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "强制重启": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.ON_COUNTER, [], category='status'),
    ],
    "当头棒喝": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.IF, [T(E.POWER_DYNAMIC, condition='enemy_switch', bonus=150)], enemy_switch=True),
    ],
    "彗星": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE), T(E.POWER_DYNAMIC, condition='self_missing_hp_step', step_pct=0.05, bonus_per_step=-10)]),
        SE(SkillTiming.POST_USE, [T(E.SELF_KO)]),
    ],
    "影袭": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "彼岸之手": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "徒长": [SE(SkillTiming.ON_USE, [T(E.HEAL_ENERGY, amount=10)])],
    "心灵洞悉": [SE(SkillTiming.ON_USE, [T(E.METEOR, stacks=1)])],
    "快速移动": [
        SE(SkillTiming.PRE_USE, [T(E.SELF_BUFF, speed=0.7)]),
        SE(SkillTiming.ON_COUNTER, [T(E.SELF_BUFF, speed=0.7)], category='defense'),
    ],
    "念力膨胀": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "怒火": [SE(SkillTiming.PRE_USE, [T(E.SELF_BUFF, atk=1.3, spatk=1.3)])],
    "怨力打击": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "恐吓": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "恶作剧": [
        SE(SkillTiming.ON_USE, [T(E.ENEMY_LOSE_ENERGY, amount=3)]),
        SE(SkillTiming.ON_COUNTER, [], category='defense'),
    ],
    "恶念交换": [],
    "恶能量": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "惊吓盒子": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.ON_COUNTER, [], category='status'),
    ],
    "感电": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "截拳": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.ON_COUNTER, [T(E.INTERRUPT)], category='status'),
    ],
    "打雪仗": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "打鼾": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "扫尾": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "扬沙": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "技巧打击": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.ON_COUNTER, [T(E.POWER_DYNAMIC, condition='counter', multiplier=10.0)], category='status'),
    ],
    "抓挠": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "折射": [SE(SkillTiming.ON_USE, [T(E.DAMAGE), T(E.POISON, stacks=2), T(E.BURN, stacks=4), T(E.FREEZE, stacks=2), T(E.METEOR, stacks=1)])],
    "折线冲击": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "抛石": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.POST_USE, [T(E.PERMANENT_MOD, target='cost', delta=-5, trigger='per_use')]),
    ],
    "报复": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.6)]),
        SE(SkillTiming.ON_COUNTER, [], category='attack'),
    ],
    "拆卸": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "拍击": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "持续高温": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.ON_COUNTER, [], category='status'),
    ],
    "指指点点": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "捆缚": [SE(SkillTiming.ON_USE, [T(E.POISON, stacks=2)])],
    "捧杀": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.9)]),
        SE(SkillTiming.ON_COUNTER, [], category='attack'),
    ],
    "掠夺": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "掩护": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.7), T(E.FORCE_SWITCH)]),
        SE(SkillTiming.ON_COUNTER, [], category='attack'),
    ],
    "提气": [SE(SkillTiming.ON_USE, [T(E.SKILL_MOD, target='self', stat='power_pct', value=0.4)])],
    "摇篮曲": [
        SE(SkillTiming.ON_USE, [T(E.SKILL_MOD, target='enemy', stat='cost', value=3)]),
        SE(SkillTiming.ON_COUNTER, [T(E.INTERRUPT)], category='defense'),
    ],
    "撒娇": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "撕咬": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.IF, [T(E.SKILL_MOD, target='self', stat='current_hit_count', value=2, condition='self_hp_below', threshold=0.5)], self_hp_below=0.5),
    ],
    "撕裂": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.ON_COUNTER, [T(E.LIFE_DRAIN, pct=1.0)], category='status'),
    ],
    "操控": [SE(SkillTiming.POST_USE, [T(E.ENEMY_ENERGY_COST_UP, amount=7, duration=3, filter='used_skill')])],
    "攻击场地": [],
    "放晴": [SE(SkillTiming.ON_COUNTER, [], category='defense')],
    "散手": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.ON_COUNTER, [], category='status'),
    ],
    "旋转突击": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "无影脚": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.ON_COUNTER, [T(E.POWER_DYNAMIC, condition='counter', multiplier=2.0)], category='status'),
    ],
    "无畏之心": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=1.0)]),
        SE(SkillTiming.ON_COUNTER, [], category='attack'),
    ],
    "易燃物质": [SE(SkillTiming.ON_USE, [T(E.DAMAGE), T(E.BURN, stacks=2)])],
    "星云漩涡": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "星星撞击": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "星轨裂变": [SE(SkillTiming.ON_USE, [T(E.METEOR, stacks=2)])],
    "星链": [SE(SkillTiming.ON_USE, [T(E.METEOR, stacks=1), T(E.SKILL_MOD, target='self', stat='hit_count', value=2)])],
    "晒太阳": [SE(SkillTiming.ON_USE, [T(E.CLEANSE, target='enemy', mode='buffs')])],
    "暗突袭": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.ON_HIT, [T(E.LIFE_DRAIN, pct=0.5)]),
        SE(SkillTiming.ON_COUNTER, [T(E.POWER_DYNAMIC, condition='counter', multiplier=2.0)], category='status'),
    ],
    "暗箱操作": [SE(SkillTiming.ON_COUNTER, [], category='defense')],
    "暴风眼": [],
    "暴风雪": [SE(SkillTiming.ON_USE, [T(E.DAMAGE), T(E.FREEZE, stacks=1)])],
    "月光合奏": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "有效预防": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.5)]),
        SE(SkillTiming.ON_COUNTER, [], category='attack'),
    ],
    "束缚": [SE(SkillTiming.ON_USE, [T(E.POISON, stacks=2)])],
    "杠杆置换": [SE(SkillTiming.ON_USE, [T(E.HEAL_ENERGY, amount=2)])],
    "极寒领域": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.ON_COUNTER, [], category='status'),
    ],
    "极速冷冻": [SE(SkillTiming.ON_COUNTER, [], category='defense')],
    "极限撕裂": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.POST_USE, [T(E.SELF_BUFF, atk=-0.5, spatk=-0.5)], self_hp_gt=0.5),
    ],
    "架势": [SE(SkillTiming.ON_USE, [T(E.HEAL_HP, pct=0.2)])],
    "柔弱": [SE(SkillTiming.PRE_USE, [T(E.ENEMY_DEBUFF, {"def": 0.7}, atk=0.7)])],
    "根吸收": [SE(SkillTiming.ON_USE, [T(E.HEAL_HP, pct=0.15)])],
    "栽赃": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "械斗": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "棘刺": [],
    "棘突": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "横纵斩": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "欺诈契约": [],
    "毒孢子": [SE(SkillTiming.ON_USE, [T(E.POISON, stacks=5)])],
    "毒沼": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "毒泡泡": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "毒针": [SE(SkillTiming.ON_USE, [T(E.DAMAGE), T(E.POISON, stacks=1)])],
    "气势一击": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.IF, [T(E.POWER_DYNAMIC, condition='prev_counter_success', bonus=240)], prev_counter_success=True),
    ],
    "气沉丹田": [
        SE(SkillTiming.PRE_USE, [T(E.SELF_BUFF, atk=1.3)]),
        SE(SkillTiming.ON_USE, [T(E.HEAL_HP, pct=0.6)]),
        SE(SkillTiming.POST_USE, [T(E.PERMANENT_MOD, target='cost', delta=-3, trigger='per_counter'), T(E.RESET_SKILL_COST, when='post_use')]),
    ],
    "气泡": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "气波": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "氧输送": [SE(SkillTiming.PRE_USE, [T(E.SELF_BUFF, spatk=0.8)])],
    "水光冲击": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "水幕冲击": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "水弹": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "水弹枪": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "水星水": [SE(SkillTiming.ON_COUNTER, [], category='status')],
    "水泡盾": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.7)]),
        SE(SkillTiming.ON_COUNTER, [T(E.SELF_BUFF, spatk=0.4)], category='attack'),
    ],
    "水波术": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "水炮": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.POST_USE, [T(E.PERMANENT_MOD, target='cost', delta=-1, trigger='per_use')]),
    ],
    "水花四溅": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "求雨": [SE(SkillTiming.ON_USE, [T(E.WEATHER, {"type": 'rain'}, turns=8)])],
    "沙涌": [SE(SkillTiming.ON_USE, [T(E.WEATHER, {"type": 'sandstorm'}, turns=8)])],
    "泡沫": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "泥巴喷射": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "泥沼": [],
    "泥浆": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "泥浆铠甲": [
        SE(SkillTiming.PRE_USE, [T(E.SELF_BUFF, {"def": 0.4}, atk=0.4)]),
        SE(SkillTiming.ON_COUNTER, [], category='defense'),
    ],
    "洗礼": [SE(SkillTiming.ON_USE, [T(E.SKILL_MOD, target='self', stat='cost', value=-1), T(E.CLEANSE, target='self', mode='debuffs')])],
    "流星火雨": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "流沙": [SE(SkillTiming.ON_COUNTER, [T(E.ENEMY_DEBUFF, {"def": 0.6}, spdef=0.6)], category='defense')],
    "流火": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "消毒法": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "涌泉": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "润泽": [SE(SkillTiming.PRE_USE, [T(E.SELF_BUFF, spatk=1.9)])],
    "淤泥表皮": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.8)]),
        SE(SkillTiming.ON_COUNTER, [], category='attack'),
    ],
    "淬火": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.7)]),
        SE(SkillTiming.ON_COUNTER, [], category='attack'),
    ],
    "湮灭": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "湿润印记": [],
    "溃烂触碰": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "溶解液": [],
    "滚雪球": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE), T(E.FREEZE, stacks=2)]),
        SE(SkillTiming.ON_COUNTER, [T(E.POWER_DYNAMIC, condition='counter', multiplier=2.0)], category='status'),
    ],
    "漫反射": [],
    "潮汐": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.6)]),
        SE(SkillTiming.ON_COUNTER, [], category='attack'),
    ],
    "潮涌": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "激怒": [SE(SkillTiming.POST_USE, [T(E.ENEMY_ENERGY_COST_UP, amount=3, duration=3, filter='other_skills')])],
    "激流": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "火云车": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "火焰冲锋": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "火焰切割": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "火焰箭": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "火爪": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "火苗": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "灵光": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.IF, [T(E.SKILL_MOD, target='self', stat='current_hit_count_mult', value=2.0, condition='enemy_switch')], enemy_switch=True),
    ],
    "灵媒": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "灼伤": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "灾厄": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.ON_COUNTER, [], category='status'),
    ],
    "炎息": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "炎打": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "炎枪": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "炎爆术": [],
    "炙热波动": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE), T(E.BURN, stacks=4)]),
        SE(SkillTiming.ON_COUNTER, [], category='status'),
    ],
    "烈焰风暴": [SE(SkillTiming.ON_USE, [T(E.DAMAGE), T(E.BURN, stacks=6)])],
    "热气": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "热砂": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "热身": [
        SE(SkillTiming.ON_USE, [T(E.NEXT_ATTACK_MOD, power_pct=1.0)]),
        SE(SkillTiming.ON_COUNTER, [], category='defense'),
    ],
    "热身运动": [SE(SkillTiming.ON_USE, [T(E.SKILL_MOD, target='self', stat='hit_count', value=3)])],
    "焚毁": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "焚烧烙印": [SE(SkillTiming.ON_USE, [T(E.BURN, stacks=5)])],
    "燃尽": [SE(SkillTiming.ON_USE, [T(E.DAMAGE), T(E.POWER_DYNAMIC, condition='self_missing_hp_step', step_pct=0.05, bonus_per_step=-5)])],
    "爆冲": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.ON_COUNTER, [T(E.POWER_DYNAMIC, condition='counter', multiplier=5.0)], category='status'),
    ],
    "爆米花爆破": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "爆裂飞弹": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "牵连": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "猛烈撞击": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "玩具乐园": [SE(SkillTiming.PRE_USE, [T(E.SELF_BUFF, speed=0.2)])],
    "球状闪电": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "甜心续航": [SE(SkillTiming.ON_USE, [T(E.HEAL_HP, pct=0.4)])],
    "生日蛋糕": [],
    "电弧": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "电流": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "电磁偏转": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.6)]),
        SE(SkillTiming.ON_COUNTER, [], category='attack'),
    ],
    "电离爆破": [SE(SkillTiming.ON_USE, [T(E.SKILL_MOD, target='self', stat='hit_count', value=3)])],
    "疾风刺": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "疾风涡轮": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "瘴气喷射": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "盛开": [
        SE(SkillTiming.ON_USE, [T(E.SKILL_MOD, target='self', stat='power_pct', value=0.3)]),
        SE(SkillTiming.ON_COUNTER, [], category='defense'),
    ],
    "瞬间零度": [SE(SkillTiming.ON_COUNTER, [T(E.ENEMY_ENERGY_COST_UP, amount=3, filter='all')], category='defense')],
    "石肤术": [SE(SkillTiming.PRE_USE, [T(E.SELF_BUFF, {"def": 1.6})])],
    "石锁": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "砂糖弹球": [],
    "破绽": [
        SE(SkillTiming.PRE_USE, [T(E.ENEMY_DEBUFF, {"def": 0.5}, spdef=0.5)]),
        SE(SkillTiming.ON_COUNTER, [T(E.SELF_BUFF, atk=0.5)], category='defense'),
    ],
    "破罐破摔": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "破防": [
        SE(SkillTiming.PRE_USE, [T(E.ENEMY_DEBUFF, {"def": 1.3}, spdef=1.3)]),
        SE(SkillTiming.ON_COUNTER, [], category='defense'),
    ],
    "硬化": [SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.9)])],
    "硬门": [SE(SkillTiming.ON_COUNTER, [T(E.INTERRUPT)], category='attack')],
    "碎冰冰": [SE(SkillTiming.ON_USE, [T(E.DAMAGE), T(E.FREEZE, stacks=1)])],
    "碎冰击": [SE(SkillTiming.ON_USE, [T(E.DAMAGE), T(E.SKILL_MOD, target='enemy', stat='cost', value=1)])],
    "碰爪": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "磁干扰": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "磁暴": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "示弱": [],
    "离子火花": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "离子震荡": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "种子弹": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "种皮爆裂": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "移花接木": [SE(SkillTiming.ON_USE, [T(E.FORCE_SWITCH)])],
    "空间压迫": [SE(SkillTiming.ON_USE, [T(E.DAMAGE), T(E.METEOR, stacks=1)])],
    "穿膛": [SE(SkillTiming.ON_USE, [T(E.DAMAGE), T(E.POWER_DYNAMIC, condition='enemy_energy_leq', threshold=2, multiplier=5.0)])],
    "突袭": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.ON_COUNTER, [T(E.POWER_DYNAMIC, condition='counter', multiplier=3.0)], category='status'),
    ],
    "等价交换": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.9)]),
        SE(SkillTiming.ON_COUNTER, [T(E.GRANT_LIFE_DRAIN, pct=0.5)], category='attack'),
    ],
    "筛管奔流": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "粒子对撞": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "精神扰乱": [
        SE(SkillTiming.ON_USE, [T(E.SKILL_MOD, target='enemy', stat='cost', value=1)]),
        SE(SkillTiming.ON_COUNTER, [T(E.ENEMY_ENERGY_COST_UP, amount=2, filter='all')], category='defense'),
    ],
    "纤维化": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.7)]),
        SE(SkillTiming.ON_COUNTER, [T(E.SELF_BUFF, {"def": 0.4})], category='attack'),
    ],
    "绵里藏针": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "缓冻": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "缠丝劲": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "网缚": [
        SE(SkillTiming.PRE_USE, [T(E.ENEMY_DEBUFF, {"def": 0.3})]),
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
    ],
    "羽刃": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.ON_COUNTER, [], category='status'),
    ],
    "羽化加速": [SE(SkillTiming.ON_USE, [T(E.AGILITY), T(E.SKILL_MOD, target='self', stat='power', value=20)])],
    "羽毛舞": [SE(SkillTiming.ON_USE, [T(E.AGILITY)])],
    "羽翼庇护": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.7)]),
        SE(SkillTiming.ON_COUNTER, [], category='attack'),
    ],
    "翅刃": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.ON_COUNTER, [], category='status'),
    ],
    "翼击": [SE(SkillTiming.ON_USE, [T(E.AGILITY), T(E.DAMAGE)])],
    "耀眼": [SE(SkillTiming.ON_USE, [T(E.SKILL_MOD, target='enemy', stat='hit_count', value=-4)])],
    "聒噪": [SE(SkillTiming.POST_USE, [T(E.ENEMY_ENERGY_COST_UP, amount=3, duration=3, filter='attack')])],
    "联动装置": [SE(SkillTiming.ON_COUNTER, [], category='defense')],
    "聚盐": [SE(SkillTiming.ON_USE, [T(E.SKILL_MOD, target='self', stat='hit_count', value=2)])],
    "肥皂泡": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "背袭": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "能量守恒": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.8)]),
        SE(SkillTiming.ON_COUNTER, [], category='attack'),
    ],
    "能量炮": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "脉冲光线": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "腐化": [
        SE(SkillTiming.PRE_USE, [T(E.ENEMY_DEBUFF, atk=0.3, spatk=0.3)]),
        SE(SkillTiming.ON_USE, [T(E.POISON, stacks=1)]),
    ],
    "腐蚀酸液": [SE(SkillTiming.ON_USE, [T(E.DAMAGE), T(E.POISON, stacks=2)])],
    "花炮": [
        SE(SkillTiming.PRE_USE, [T(E.SELF_BUFF, spatk=0.5)]),
        SE(SkillTiming.ON_USE, [T(E.SKILL_MOD, target='self', stat='hit_count', value=2)]),
    ],
    "花香": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "芳香诱引": [
        SE(SkillTiming.ON_USE, [T(E.SKILL_MOD, target='self', stat='hit_count', value=3)]),
        SE(SkillTiming.ON_COUNTER, [T(E.INTERRUPT)], category='defense'),
    ],
    "荆棘爪": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "荟萃": [],
    "落井下毒": [],
    "落星": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "落石": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "落雨": [SE(SkillTiming.ON_USE, [T(E.WEATHER, {"type": 'rain'}, turns=8)])],
    "落雷": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "蓄势待发": [],
    "蓄水": [],
    "蓄能轰击": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "藤绞": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "藤鞭": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "虚假破产": [SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.8)])],
    "虚化": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.7)]),
        SE(SkillTiming.ON_COUNTER, [T(E.SELF_BUFF, spdef=0.4)], category='attack'),
    ],
    "虫击": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.ON_COUNTER, [T(E.POWER_DYNAMIC, condition='counter', multiplier=2.0)], category='status'),
    ],
    "虫刺": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "虫结阵": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.6)]),
        SE(SkillTiming.ON_COUNTER, [], category='attack'),
    ],
    "虫网": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "虫群": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "虫群智慧": [],
    "虫群过境": [SE(SkillTiming.ON_USE, [T(E.DAMAGE), T(E.SKILL_MOD, target='self', stat='hit_count', value=1)])],
    "虫茧": [SE(SkillTiming.ON_USE, [T(E.HEAL_HP, pct=0.2)])],
    "虫蛊": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "虫鸣": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "虹光冲击": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "蛰针": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "蜡质膜": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.7)]),
        SE(SkillTiming.ON_COUNTER, [], category='attack'),
    ],
    "血气": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.6)]),
        SE(SkillTiming.ON_COUNTER, [], category='attack'),
    ],
    "裂石": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.ON_COUNTER, [T(E.ENEMY_DEBUFF, {"def": 0.8})], category='status'),
    ],
    "见招拆招": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.IF, [T(E.POWER_DYNAMIC, condition='prev_status', bonus=50)], prev_status=True),
    ],
    "角击": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "触底强击": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.IF, [T(E.POWER_DYNAMIC, condition='energy_zero_after_use', bonus=100)], energy_zero_after=True),
    ],
    "触电": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "许愿星": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "诋毁": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "诡刺": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "贪婪": [SE(SkillTiming.ON_USE, [T(E.GRANT_LIFE_DRAIN, pct=1.0)])],
    "贮藏": [SE(SkillTiming.PRE_USE, [T(E.SELF_BUFF, atk=0.5, spatk=0.5)])],
    "贯手": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "赤子之心": [SE(SkillTiming.ON_USE, [T(E.HEAL_HP, pct=0.4)])],
    "趁火打劫": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "超导": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "超导加速": [
        SE(SkillTiming.PRE_USE, [T(E.SELF_BUFF, speed=0.3)]),
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
    ],
    "超新星馈赠": [SE(SkillTiming.ON_USE, [T(E.METEOR, stacks=2)])],
    "超级糖果": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "超维投射": [SE(SkillTiming.ON_USE, [T(E.METEOR, stacks=4)])],
    "跌落": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.ON_COUNTER, [T(E.SELF_BUFF, atk=0.5)], category='status'),
    ],
    "践踏": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "跺地": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "过曝": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "过载回路": [SE(SkillTiming.ON_USE, [T(E.FORCE_SWITCH)])],
    "远程访问": [SE(SkillTiming.ON_USE, [T(E.FORCE_ENEMY_SWITCH)])],
    "连续毒针": [SE(SkillTiming.ON_USE, [T(E.DAMAGE), T(E.POISON, stacks=1)])],
    "连续爪击": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.ON_COUNTER, [T(E.SKILL_MOD, target='self', stat='current_hit_count_mult', value=2.0)], category='status'),
    ],
    "迫害": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "迫近攻击": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.POST_USE, [T(E.PERMANENT_MOD, target='power', delta=40, trigger='per_use')]),
    ],
    "追打": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.ON_COUNTER, [], category='status'),
    ],
    "退化": [],
    "逆向演化": [],
    "逆袭": [SE(SkillTiming.ON_USE, [T(E.DAMAGE), T(E.POWER_DYNAMIC, condition='energy_cost_above_base', base_cost=3, bonus_per_step=45)])],
    "透射": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "速冻": [],
    "遁地": [SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.5)])],
    "酶浓度调整": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.7)]),
        SE(SkillTiming.ON_COUNTER, [], category='attack'),
    ],
    "重击": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.POST_USE, [T(E.PERMANENT_MOD, target='cost', delta=1, trigger='per_use')]),
    ],
    "金属噪音": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "针状物": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "钢钻": [],
    "钢铁洪流": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "钧势": [SE(SkillTiming.PRE_USE, [T(E.SELF_BUFF, {"def": 1.4})])],
    "错乱": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.ON_COUNTER, [], category='status'),
    ],
    "镜像反射": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.8)]),
        SE(SkillTiming.ON_COUNTER, [], category='attack'),
    ],
    "闪光": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "闪光冲击": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "闪击": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "闪击折返": [SE(SkillTiming.ON_USE, [T(E.DAMAGE), T(E.FORCE_SWITCH)])],
    "闪燃": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.ON_COUNTER, [T(E.POWER_DYNAMIC, condition='counter', multiplier=4.0)], category='status'),
    ],
    "防反": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.6)]),
        SE(SkillTiming.ON_COUNTER, [T(E.SELF_BUFF, atk=0.4, spatk=0.4)], category='attack'),
    ],
    "防御反击": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.8)]),
        SE(SkillTiming.ON_COUNTER, [T(E.SKILL_MOD, target='self', stat='power_pct', value=0.4)], category='attack'),
    ],
    "阳火增辉": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "降灵": [],
    "除厄": [SE(SkillTiming.ON_USE, [T(E.DAMAGE), T(E.CLEANSE, target='self', mode='buffs')])],
    "陨石": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "隐藏条款": [],
    "隼鳞": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "集中": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.7)]),
        SE(SkillTiming.ON_COUNTER, [], category='attack'),
    ],
    "雪替身": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.7)]),
        SE(SkillTiming.ON_COUNTER, [], category='attack'),
    ],
    "雪球": [SE(SkillTiming.ON_USE, [T(E.SELF_BUFF, speed=-0.9)])],
    "雷暴": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "雾气环绕": [],
    "震击": [SE(SkillTiming.ON_USE, [T(E.DAMAGE), T(E.SKILL_MOD, target='enemy', stat='hit_count', value=-3)])],
    "霜冻": [SE(SkillTiming.PRE_USE, [T(E.ENEMY_DEBUFF, spdef=1.0)])],
    "霜天": [SE(SkillTiming.ON_USE, [T(E.FREEZE, stacks=3)])],
    "霜降": [SE(SkillTiming.ON_USE, [T(E.FREEZE, stacks=4)])],
    "鞭打": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "音波弹": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "音爆": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "顶端优势": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "预备势": [
        SE(SkillTiming.PRE_USE, [T(E.SELF_BUFF, atk=0.8)]),
        SE(SkillTiming.ON_COUNTER, [T(E.ENEMY_DEBUFF, {"def": 0.8})], category='defense'),
    ],
    "风吹雪": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "风矢": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "风起": [],
    "风隐": [SE(SkillTiming.ON_USE, [T(E.FORCE_SWITCH)])],
    "飞叶": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "飞吻": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "飞断": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "飞羽": [SE(SkillTiming.ON_USE, [T(E.AGILITY)])],
    "飞踢": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "食腐": [],
    "骗局": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "高温回火": [SE(SkillTiming.ON_USE, [T(E.DAMAGE), T(E.FORCE_SWITCH)])],
    "鬼火": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "魅惑": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "魔法增效": [SE(SkillTiming.PRE_USE, [T(E.SELF_BUFF, spatk=0.7)])],
    "魔爪": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "魔能爆": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "鸣叫": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "鸣沙陷阱": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "鸩毒": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE), T(E.POISON, stacks=1)]),
        SE(SkillTiming.ON_COUNTER, [], category='status'),
    ],
    "鹰爪": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "麻痹": [
        SE(SkillTiming.ON_USE, [T(E.SKILL_MOD, target='enemy', stat='priority', value=-1)]),
        SE(SkillTiming.ON_COUNTER, [], category='defense'),
    ],
    "黑手": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "鼓劲": [SE(SkillTiming.PRE_USE, [T(E.SELF_BUFF, spdef=1.5)])],
    "齿轮切开": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "龙之利爪": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.ON_HIT, [T(E.LIFE_DRAIN, pct=0.5)]),
    ],
    "龙之舞": [],
    "龙卷风": [
        SE(SkillTiming.ON_USE, [T(E.AGILITY), T(E.DAMAGE)]),
        SE(SkillTiming.ON_COUNTER, [], category='status'),
    ],
    "龙吟": [SE(SkillTiming.PRE_USE, [T(E.SELF_BUFF, atk=1.0, spatk=1.0, speed=0.6)])],
    "龙吼": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "龙威": [],
    "龙息环爆": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE)]),
        SE(SkillTiming.ON_COUNTER, [], category='status'),
    ],
    "龙炮": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "龙爪": [SE(SkillTiming.ON_USE, [T(E.DAMAGE)])],
    "龙血": [
        SE(SkillTiming.ON_USE, [T(E.DAMAGE_REDUCTION, pct=0.6)]),
        SE(SkillTiming.ON_COUNTER, [], category='attack'),
    ],
}
